### ISSUE TITLE
carousel images not displaying properly for the mobile view

### ISSUE THREAD

**Issue by ozair-kmit** [AbhinavaReddy-hub/Plant-Disease-Detection-System#1]
### 
> **in the mobile view , carousel images at left side are overlapping with button**

![image](https://github.com/user-attachments/assets/44e8f0ae-2d04-4ce3-b11f-333978b6e451)

**Comment by ShahrukhSiddiq** [comment]
> Okay, Let us Fix it!

**Comment by ozair-kmit** [comment]
resolved this issue ,and merged to sort branch

**Comment by AbhinavaReddy-hub** [comment]
Great! 👍
